import * as React from "react";
import { useLoaderData } from "react-router";

import { SystemInfo } from "@/components/SystemInfo.tsx";

export default function About() {
  const { platform, arch }: ISystemInfo = useLoaderData();

  return (
    <div className="p-4">
      <h1 className="my-2 text-2xl">About</h1>
      <p className="text-sm">This route is generated by React Router.</p>
      <SystemInfo platform={platform} arch={arch} />
    </div>
  );
}
