import * as React from "react";

import { SynthesizerTester } from "@/components/SynthesisTester.tsx";

export default function Synthesizer() {
  return (
    <div className="p-4">
      <h1 className="my-2 text-2xl">Speech Synthesizer</h1>
      <p className="text-sm">Text-To-Speech generated by system speech synthesizer.</p>
      <SynthesizerTester />
    </div>
  );
}
